name: DemoAppp/eshop/eshop-observability
on:
  workflow_dispatch:
jobs:
  Stage-1:
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: "${{ secrets.AZURE_CREDENTIALS }}"
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: eshoponweb-mcp
        package: drop/*.zip
