name: eshop-observability1
"on":
  push:
    branches:
    - main
  workflow_dispatch: {}
env:
  artifactName: drop
  zipName: webapp.zip
  buildConfiguration: Release
jobs:
  build:
    steps:
    - uses: actions/checkout@v6.0.1
      name: checkout
    - uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
      name: Use .NET SDK
    - run: |
        dotnet restore
        dotnet build --configuration ${{ env.buildConfiguration }}
        dotnet publish src/Web/Web.csproj \
          --configuration ${{ env.buildConfiguration }} \
          --output ${{ github.workspace }}
      name: Build & Publish ASP.NET app
    - run: |
        echo "Zipping the build output..."
        zip -r ${{ runner.temp }}/${{ env.zipName }} ${{ github.workspace }} -x *.git* node_modules/*
      name: Create ZIP Artifact
    - uses: actions/upload-artifact@v4
      with:
        path: ${{ runner.temp }}/${{ env.zipName }}
        name: ${{ env.artifactName }}
      name: Publish artifact ${{ env.artifactName }}
    runs-on: ubuntu-latest

